# src/OpenClassRoom/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:     /{page}
    defaults:
        _controller: OpenClassRoomPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*


oc_platform_view:
    path:     /advert/{id}
    defaults:
        _controller: OpenClassRoomPlatformBundle:Advert:view
    requirements:
        id: \d+


oc_platform_add:
    path:     /add
    defaults:
        _controller: OpenClassRoomPlatformBundle:Advert:add


oc_platform_edit:
    path:     /edit/{id}
    defaults:
        _controller: OpenClassRoomPlatformBundle:Advert:edit
    requirements:
        id: \d+


oc_platform_delete:
    path:     /delete/{id}
    defaults:
        _controller: OpenClassRoomPlatformBundle:Advert:delete
    requirements:
        id: \d+


