# src/OpenClassRoom/PlatformBundle/Resources/config/services.yml

services:
  oc_platform.antispam:
    class: OpenClassRoom\PlatformBundle\Antispam\OCAntispam
    arguments:
      - "@mailer"
      - "%locale%"
      - "50"

  oc_platform.validator.antiflood:
    class: OpenClassRoom\PlatformBundle\Validator\AntifloodValidator
    arguments:
      - "@request_stack"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: validator.constraint_validator, alias: oc_platform_antiflood }

  oc_platform.twig.antispam_extension:
    class: OpenClassRoom\PlatformBundle\Twig\AntispamExtension
    arguments:
      - "@oc_platform.antispam"
    tags:
      - { name: twig.extension }

  oc_platform.form.ckeditor:
    class: OpenClassRoom\PlatformBundle\Form\CkeditorType
    tags:
      - { name: form.type, alias: ckeditor }

  oc_platform.beta.html_adder:
    class: OpenClassRoom\PlatformBundle\Beta\BetaHTMLAdder

  oc_platform.beta.listener:
    class: OpenClassRoom\PlatformBundle\Beta\BetaListener
    arguments:
      - "@oc_platform.beta.html_adder"
      - "2018-11-15"
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: processBeta, priority: 2 }

  oc_platform.bigbrother.message_notificator:
    class: OpenClassRoom\PlatformBundle\BigBrother\MessageNotificator
    arguments:
      - "@mailer"

  oc_platform.bigbrother.message_listener:
    class: OpenClassRoom\PlatformBundle\BigBrother\MessageListener
    arguments:
      - "oc_platform.bigbrother.message_notificator"
      - ["alexandre", "marine", "pierre"]
    tags:
      - { name: kernel.event_subscriber }

  oc_platform.paramconverter.json:
    class: OpenClassRoom\PlatformBundle\ParamConverter\JsonParamConverter
    tags:
      - { name: request.param_converter }