services:
  oc_platform.antispam:
    class: OpenClassRoom\PlatformBundle\Antispam\OCAntispam
    arguments:
      - "@mailer"
      - "%locale%"
      - "50"

  oc_platform.validator.antiflood:
    class: OpenClassRoom\PlatformBundle\Validator\AntifloodValidator
    arguments:
      - "@request_stack"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: validator.constraint_validator, alias: oc_platform_antiflood }