# src/OpenClassRoom/UserBundle/Resources/config/services.yml

services:
#    user.example:
#        class: OpenClassRoomUserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
